title: My tech page
author: udhayaprabakaran
email: udhayudo@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  The site is about my technologies I learned and sharing the 
  same with you'all.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
